characters = [
    {
        "index": 0,
        "class": "sorceress",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "arcana",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "summoner",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "sorceress",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "bard",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "gunslinger",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 11,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 12,
        "class": "deathblade",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
]
